#### general settings
MODEL:
  image_model_name: 'net_image'
  video_model_name: 'net_video'
  n_feats: 16

TESTING:
  gpu_ids: [0]
  checkpoint_path: './checkpoints'
  result_path: './results/'
  num_frames: 5

#### datasets
DATASETS:
  test:
    dataset_name: 'UVEB'# UVEB DRUVA
    raw_root: '../../../share/UIE/datasets/test/'
    size: [320, 240]
    use_shuffle: false